### ISSUE TITLE
does it support kafka 0.10.X?

### ISSUE THREAD

**Issue by lifuchao** [spring-projects/spring-integration-kafka#129]
as the title say?
urgent,thanks

**Comment by garyrussell** [comment]
We are planning on releasing a 2.1 milestone to support 0.10.x shortly - we already have a [pull request for the underlying spring-kafka project](https://github.com/spring-projects/spring-kafka/pull/121).

**Comment by george-smith** [comment]
Gary. Any update on the 2.1 support for 0.10.x? And will there be an update to the spring boot kafka starter to support this as well?

**Comment by garyrussell** [comment]
@george-smith Sorry - we found we didn't need any changes to s-i-k. 2.0.1 works with the [`spring-kafka` 1.1.0 milestone release](https://spring.io/blog/2016/08/23/spring-for-apache-kafka-1-1-0-milestone-1-available) which supports the 0.10.x.x client. Simply override the transitive version. The milestone repo can be found on [the project page](http://projects.spring.io/spring-kafka/) - select 1.1.0.M1 in the "Quick Start" drop down.

We already upgraded the [Spring Integration Sample App](https://github.com/spring-projects/spring-integration-samples/commit/b6cbf15e4c9cdb8ef1d6440494927b7d6066f112).

**Comment by artembilan** [comment]
We realized that with a new `batching` support in Spring Kafka 1.1, Spring Integration Kafka isn't compatible any more.
So, we [have just started](https://github.com/spring-projects/spring-integration-kafka/commit/dde8d890bfa6f9f2cfa4fbce59c7053df2b48744) version `2.1` fully based on SK-1.1, which uses Kafka 0.10.x already.

Therefore I consider this issue as fixed with that.

**Comment by garyrussell** [comment]
We plan on releasing 2.1.0.M1 today or tomorrow (and M2 for spring-kafka 1.1).
