### ISSUE TITLE
spring.kafka.listener properties are not applied to Kafka.messageDrivenChannelAdapter

### ISSUE THREAD

**Issue by mrusinak** [spring-projects/spring-integration-kafka#204]
In version 3.0.1.RELEASE, listener properties (such as concurrency, poll-timeout/thresholds, etc) are not applied when using spring-integration/java-dsl to create Kafka consumers.

While it is possible to apply them manually as a workaround, (https://stackoverflow.com/questions/50235548/spring-kafka-concurrency-with-spring-integration), it gets complicated to do so for a couple reasons:

1. The `KafkaMessageDrivenChannelAdapterListenerContainerSpec` does not have parity to all the options, so it winds up being required to use a `Kafka.messageDrivenChannelAdapter` variant that takes a `ContainerProperties` - none of which allow specifying the Topic separately
1. There is no publicly usable method as far as I can tell to create a `ContainerProperties` out of `KafkaProperties`
1. Copying `ContainerProperties` is buried in configuring a new instance of a container, requiring playing games by extending classes, or by the application copy/pasting the logic - neither option feels good

Ideally the listener properties should be applied correctly without the application needing to do anything, but otherwise having a way for an application to easily create `ContainerProperties` from `KafkaProperties` would be a huge help.

**Comment by artembilan** [comment]
Unfortunately you are missing the fact that `KafkaProperties` properties is a part of Spring Boot project: https://projects.spring.io/spring-boot/. This one is a pure Spring Integration implementation for the Spring for Kafka project. That is a convention in Spring Boot to auto-configuration something for us based on the configuration properties. Here we deal with regular Spring Inversion of Control container: there is no any auto-configurations.

The idea about `ContainerProperties` extracting from the `KafkaProperties` does not make sense as well.
See it's ctors:
```
public ContainerProperties(String... topics) {
}

public ContainerProperties(Pattern topicPattern) {
}

public ContainerProperties(TopicPartitionInitialOffset... topicPartitions) {
}
```
So, the `topic` <-> `ContainerProperties` is one-to-one relationship.

I know it might be a bit complicated to figure how to configure everything, but that's was the best we could come up for Spring-based code style.

**Comment by mrusinak** [comment]
I did completely miss that KakaProperties was from springboot, that's quite unfortunate.

In that case, would it be possible to add a variation of `Kafka.messageDrivenChannelAdapter` that can accept a  `ConcurrentKafkaListenerContainerFactory` so that internally when it's building it's `KafkaMessageListenerContainerSpec`, it could copy the `ContainerProperties` defined in that factory?

Then a springboot application could easily autowire in the `ConcurrentKafkaListenerContainerFactory`, and construct an integration flow via `Kafka.messageDrivenChannelAdapter(factory, "some-topic")` from the auto-configuration already done by springboot.

**Comment by garyrussell** [comment]
Interesting, yes, I guess that would work; it's a bit of an abuse, though, since it's not really a factory in that case, just a mechanism for passing properties around.

If we were to do this, I would prefer to pull that functionality (properties holder) to a super class (e.g. `ContainerConfigurationHolder` and have the current factory be a subclass of that and have the DSL accept a `ContainerConfigurationHolder`.

**Comment by garyrussell** [comment]
I am not comfortable with adding a DSL method that takes a `ConcurrentKafkaListenerContainerFactory` since it's not really used as a factory.

The refactoring would be in spring-kafka, and the DSL improvement would need to be here. I don't think we need another issue over there.

Give us some time to discuss internally and we'll get back to you in a day or so.

**Comment by garyrussell** [comment]
I think I've come up with a reasonable compromise - extend the container factory so it can create any container based on the boot properties, even for containers that aren't used for `@KafkaListener`s.

PoC here: https://github.com/garyrussell/spring-kafka/commit/59b96ca8b41a77dec8f353983c98310aed82aed8

@artembilan WDYT?

**Comment by artembilan** [comment]
Let's give it a shot, Gary!

Looks very promising.  I guess we would need to fix JavaDocs on that factory and also say something in the Docs.

**Comment by rajeshsharmaacs** [comment]
Hi there, 
I have kind of similar issue, and found this issue more closer to problem I am facing.

Gradle (specific to these version, because of package `...springframework.integration.kafka.dsl.Kafka`;
```
compile("org.springframework.integration:spring-integration-amqp:5.0.7.RELEASE")
compile('org.springframework.kafka:spring-kafka:2.1.8.RELEASE')
```

```
@Bean
    @IfJobEnabled(JOB_NAME)
    protected IntegrationFlow integrationFlow() {
        registerJob();
        return IntegrationFlows
                .from(Kafka.messageDrivenChannelAdapter( consumerFactory(), "kafka-topic")).
                        filter(v -> !batchManager.isStopping()).
                        transform(context.getBean(ByteArrayToJsonObjTransformer.class)).
                        handle(msg -> batchManager.runJob(JOB_NAME, BatchUtils.jobParamsFromKafkaMsg(msg))).get();
    }

```

When starting the batch, getting `IllegalArgumentException`
`Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.integration.support.management.IntegrationManagementConfigurer]
`

**Comment by garyrussell** [comment]
Please don't piggy-back on 2 year old issues; this is clearly unrelated to the subject of this issue.

It's better to ask such questions on stack overflow, tagged with spring-integration and spring-kafka.

You need to show ALL the dependencies and the full stack trace.
