### ISSUE TITLE
Move to spring-integration repo

### ISSUE THREAD

**Issue by sparty02** [spring-projects/spring-integration-kafka#304]
Would you consider moving this to the [spring-integration repo](https://github.com/spring-projects/spring-integration)?  Outside of logically sitting next to the other modules, the practical issue I'm currently hitting is that its not picked up in the spring-integration-bom, which means I unfortunately have to fiddle with managing a version for it, which also lowers some confidence on which versions have been "certified" together.

**Comment by artembilan** [comment]
Thanks for sharing your pain with us!

Unfortunately we can't do that because Spring Integration main project has different release cycle from this project.
And since this project is fully based on the Apache Kafka release cadence, we can't keep them together in the longer releases of Spring Integration.

Also this is not only one Spring Integration extension which has its own release scope.
See more here: https://github.com/spring-projects/spring-integration-extensions.

We probably may think about having `spring-integration-bom` as a separate project which would manage versions for main Spring Integration modules as well as all the supported extensions.
But that's hard matter and needs thorough investigation...

@garyrussell , WDYT?

**Comment by garyrussell** [comment]
That was my initial thought; but things have been quite stable for a while so it might be possible; especially if you plan SI releases aligned with Boot's current cadence.

It's maybe too late for 5.3, but we could consider it in 5.4.

**Comment by artembilan** [comment]
See here: https://jira.spring.io/browse/INT-3966

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/b860a2e818f06a9895ba80b0485e5f073b63c494
