### ISSUE TITLE
ProducerMetadata.setPartitioner() has not effect.

### ISSUE THREAD

**Issue by abhijith-prabhakar** [spring-projects/spring-integration-kafka#67]
KafkaProducerMessageHandler uses overloaded send() method from KafkaProducerContext which makes setting partitioner on ProducerMetadata useless.

**Comment by artembilan** [comment]
Agreed. That's some kind of bug which is just not covered by tests.
Which version of Spring Integration Kafka do you use to provide the fix for you?

In additional I see that XSD requests `partition-id-expression`, but the parser's code is like:
````java
kafkaProducerMessageHandlerBuilder.addPropertyValue("partitionIdExpression", partitionIdExpressionDef);
````
So, this one should be fixed, too.

The original issue can be fixed like moving the `Partitioner` logic to the `ProducerConfiguration.send(String topic, Integer partition, K messageKey, V messagePayload)` method when `partition == null`.

WDYT?

And thank you for the report!

**Comment by abhijith-prabhakar** [comment]
Thank you for the quick response.  I am working on latest version 1.2.1.RELEASE.  

Yes, pushing partitioner logic would work, but what will happen if user sends partition number as well? We could do couple of things.  
1. Put default precedence to user input and select custom partitioner only in case of `Integer partition` is null
2. Throw an exception saying to user that you could do only one option. Either set custom partitioner or send partitionid in request.
Personally I prefer second option.

**Comment by artembilan** [comment]
Well, the fallback option is always good choice!

I'm happy if we have something similar implementing some protocol adapter :smile: 
Because in the messaging environment there really no guaranty that all sending messages will have particular header or some required system state causes.

So, +1 for the first option!

**Comment by abhijith-prabhakar** [comment]
I am fine either way.  Do you want me to fix it and issue a pull request??

**Comment by artembilan** [comment]
:+1: Yes, that would be cool!
Please, follow with the https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md

**Comment by abhijith-prabhakar** [comment]
Thanks...will do

**Comment by artembilan** [comment]
Hello, @abhijith-prabhakar !

Hope you are well.

Just as a reminder note :smile: 
Let us know if you are still interested in the contribution or we should do this ourselves.

Thanks in advance!

**Comment by abhijith-prabhakar** [comment]
Sorry for my delayed response.  I was getting clearance from company to sign ICL.  Will send my pull request soon.

**Comment by abhijith-prabhakar** [comment]
Has issued the pull request:  https://github.com/spring-projects/spring-integration-kafka/pull/71

Has signed ICA, added tests and all tests are passing locally.

**Comment by mbogoevici** [comment]
I don't think we should support this. `Partitioner` is part of the old Kafka producer API and we shouldn't mix it with the new.

**Comment by mbogoevici** [comment]
Or if we do, the same way as with `Encoder`, it should be deprecated and remove in the next major version.

**Comment by artembilan** [comment]
So, let's start our `1.3` version!
Or do we wait for something like ` 0.9.0.0` from Apache Kafka (see their JIRA (https://issues.apache.org/jira/browse/KAFKA))?

Although with that I'd say that we should start our `2.0`...

**Comment by mbogoevici** [comment]
Yeah, that's the sanest course. Let's merge this for 1.x and deprecate the old APIs in 2.0. Said something similar here: https://github.com/spring-projects/spring-integration-kafka/issues/63#issuecomment-146684817

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-projects/spring-integration-kafka/commit/4786b64f51443ff788e8985fbbf12857cf435378
