### ISSUE TITLE
Notify producer message delivery status to caller

### ISSUE THREAD

**Issue by sharpnk** [spring-projects/spring-integration-kafka#86]
Not sure if this technically qualify as an issue, but I am trying to figure out what's the best way to incorporate the new ProducerListener in my project. In my use case, I need to send out a bunch of messages to Kafka broker in strict order. If one of those messages failed to be delivered to the broker, the caller needs to be notified and stops all subsequent requests. ProducerListener looks like a great candidate to solve my problem and guarantee the delivery order.

I created a ProducerListener and assigned it to the producer configuration. The caller sends these messages to a MessageChannel which is wired up to a outbound-channel-adapter. Ideally, the caller should be notified of whether the message delivery to the broker is successful or not. However, because the ProducerListener and its callbacks are pre-defined with the producer configuration, I found myself stuck in a place where I can't get the call back to properly notify the caller.

To go around this, I added a ConcurrentHashSet in the the ProducerListner and keep track of all the failed delivery attempt. This way the caller will be able to check it next time it tries to send messages. This is far from ideal though.

Any suggestions on this? I am just curious if I am using it as it's intended to be. Thanks.

**Comment by artembilan** [comment]
Well, that doesn't look like a Framework issue, really. It is just a business task of the target application.

From one side it looks like you would like to reach some functionality which we have with AMQP or JMS (quoting @mbogoevici :smile: ). Just because Kafka is intended for a bit different messaging tasks, like send and forget: the delivery is guaranteed by the cluster for Kafka Brokers and so on.

I'd implement your task as **batch of messages**, if the order is important, because it is better to try to achieve the messaging architecture in your application when one messages doesn't impact other message. Hence we get a gain from the Kafka **async** nature. In this case you will have your full batch rejected and `ProducerListner.onError()` will allow you fallback somehow it further. And again: in the async manner.

From other side you can make your producer sequential and single threaded and don't publish the next message to Kafka until the `ProducerListner` doesn't say you about the delivery or error of previous one. 

You can achieve that with the `Semaphore(1)` (or some other synchronizer which you want) and `release()` from the `ProducerListner.onSuccess()`. With the `ProducerListner.onError()` you can `stop()` the sender and cancel the current waiting message.

Hope I am clear.

**Comment by sharpnk** [comment]
@artembilan Great explanation. Thanks!
