### ISSUE TITLE
KafkaMessageListenerContainer cache fetchOffsets having issue with circuit breaker

### ISSUE THREAD

**Issue by lesongjia** [spring-projects/spring-integration-kafka#90]
Hey, 

I had an issue when apply circuit breaker around my consumer runnable. With circuit breaker, when my consumer logic throws any exception, the circuit will be open and the request will be short circuited. The problem I had is when the circuit is back from open to close KafkaMessageListenerContainer will not fetch from the last failure log. I dig into the code and found KafkaMessageListenerContainer caching the fetchOffsets after it is init. I see why it caches the offsets and it does make sense. 

My current work around is to stop the container, wait a few seconds and restart the container in my circuit breaker fallback logic. Since every time it is init, it will ask OffsetManager for all the offsets. 

My question is whether there is other good solutions that I did not catch. Also, I am using the topic offset manager and I do not care to read the offset every time. Can somehow that I can turn off the offset cache in KafkaMessageListenerContainer? 

Thank you.

**Comment by enzomotta** [comment]
Hi, any update on this?
I have the same issue and I'm thinking about doing something similar (to restart the container).

**Comment by artembilan** [comment]
Restarting the container is wise solution and since we have already moved to Kafka 0.9 [support](https://spring.io/blog/2016/07/04/spring-for-apache-kafka-1-0-and-spring-integration-kafka-2-0-go-ga), it would be great to ask you guys, to revise your solution with a new Spring Integration Kafka 2.0 foundation.

We don't have `OffsetManager` support there [yet](https://github.com/spring-projects/spring-kafka/issues/9), so I'm curious how is it going with a new architecture.

Closing this one since we don't provide any new feature for Kafka 0.8 support. If there is some reasonable workaround.
